### ISSUE TITLE
Refatoração da interface

### ISSUE THREAD

**Issue by bismarckjunior** [PHydra/Hydra#1]
- [x] Tubos e Sapatas
- [x] Litologia
- [x] Geopressões
- [ ] Perfil térmico
  - [x] Desenhar layout 
  - [x] Criar janelas
  - [x] Criar botões
  - [x] Testar
  - [ ] Inserir itens na tree
- [ ] Eventos
  - [x] Tabela Etapas
  - [x] Tabela Eventos
  - [x] Criar botões
  - [x] Conexões
  - [x] Testar
  - [ ] Inserir itens na tree
- [ ] Análises
  - [x] Criar orientação a objeto
  - [ ] Criar Layouts
  - [x] Criar janela de criação
  - [ ] Definir análises
- [x] Ícones
  - [x] Miniatura na tree
  - [x] Remover linha na tabela
- [ ] Linkar com kernel
- [ ] Testar escrita em arquivo
- [ ] Testar leitura em arquivo

**Comment by bismarckjunior** [comment]
Em andamento.

**Comment by bismarckjunior** [comment]
Criado a classe HyComboBoxFrame (genérica) e uma para dados especificos em tubos e sapatas.
Proxímo passo: Inserir comboBox na aba "Eventos" associando ao botões.

**Comment by PHydra** [comment]
Esta issue será encerrada, pois será dividida em diversas outras issues a fim de detalhar mais o projeto.
