### ISSUE TITLE
Implementar tela de TEMPERATURA e GEOPRESSÕES

### ISSUE THREAD

**Issue by jorelanjos** [PHydra/Hydra#10]
Seguir recomendações abaixo
[[2016.12.19] Plug-in_Integridade_Gtep_19Dezembro2016_TEMPERATURA E GEOPRESSÕES.pptx](https://github.com/PHydra/Hydra/files/793538/2016.12.19.Plug-in_Integridade_Gtep_19Dezembro2016_TEMPERATURA.E.GEOPRESSOES.pptx)

**Comment by bismarckjunior** [comment]
Boa parte das sugestões já foram implementadas na nova versão. Acredito que a única implementação pendente seja a de criar um subitem para cada perfil térmico criado dentro do item **Perfil Térmico**. Esta tarefa pode ser acompanhada na Issue #1.

**Comment by jorelanjos** [comment]
Perfeito então, essa _issue_ está para fins de registro.

Vou testar a nova versão e comento aqui qualquer necessidade.

**Comment by bismarckjunior** [comment]
Não será mais criado subitens dentro do item **Perfil Térmico**, a menos que seja solicitado.

**Comment by jorelanjos** [comment]
PEssoal, vejam que existe um erro ortográfico na palavra **_Overburden_**
![erro](https://user-images.githubusercontent.com/22779284/26994281-590379d4-4d3d-11e7-8e4c-60015db2e780.PNG)
.
