### ISSUE TITLE
GUI: Correção da pressão de poros e profundidade do Sal

### ISSUE THREAD

**Issue by danielduquemelo** [PHydra/Hydra#100]
- [x] Se o usuário não criar um ponto imediatamente acima da camada de sal, a interface deve criá-lo para evitar interpolação errada da pressão de poros

- [x] Ponto extra: Topo do Sal - 0.01 metros, por exemplo. Apenas para gerar a descontinuidade da pressão de poros
![capturar](https://user-images.githubusercontent.com/25479928/34528374-e854f496-f08f-11e7-85c8-dea3f5e0c8ad.PNG)

-  [x] Criação de um novo item "HyTables_GeoPressures"

**Comment by ismaelpimentel** [comment]
Feito.
