### ISSUE TITLE
Bug na hora de delatar uma linha da tabela tubos e sapatas.

### ISSUE THREAD

**Issue by ismaelpimentel** [PHydra/Hydra#109]
- [x] - Ao deletar uma linha na tabela tubos e sapatas está dando problema, inclusivo não está sendo eliminado da tabela etapas do item etapas e eventos.  A ideia é que ao eliminar uma linha da tabela geral de tubos e sapatas essa linha deveria automaticamente ser eliminado tanto da tabela especifica de tubos e sapatas como na tabela etapas do item etapas e eventos.

**Comment by danielduquemelo** [comment]
delete do botão direito desabilitado.
