### ISSUE TITLE
Seleção da profundidade em interfaces

### ISSUE THREAD

**Issue by JDVelilla** [PHydra/Hydra#126]
Ao selecionar os dados para o modelo, o kernel pega o seguinte em casos de interface do modelo. 

Pegar o valor anterior!

**Comment by danielduquemelo** [comment]
Seleção defalut quando se está num ponto de interface de camada (ou Sapata, ou TOC):
1- pega camada de cima
2- considera o revestimento quando na sapata
3- considera o cimento quando no TOC
