### ISSUE TITLE
Trocar o viewport para a última análise criada

### ISSUE THREAD

**Issue by JDVelilla** [PHydra/Hydra#127]

**Comment by danielduquemelo** [comment]
KERNEL:
Ao criar uma análise, são feitos dois Viewports da análise distribuidos horizontalmente.
1- Mesh Viewport: com a malha definida
2- Material Viewport:  com os materiais

O viewport default do Abaqus ("Viewport:1") continua existindo, mas é minimizado e colocado em segundo plano.

Futuramente, o ideal é que a Interface altere os viewports sempre que for selecionada uma análise.
