### ISSUE TITLE
Atualizar peso de lama do poço revestido

### ISSUE THREAD

**Issue by JDVelilla** [PHydra/Hydra#129]
o peso de lama da primeira linha da tabela poço revestido deve ser atualizado com o peso da ultima etapa do poço aberto

**Comment by ismaelpimentel** [comment]
Feito.

**Comment by danielduquemelo** [comment]
Esta issue não está funcionando!

**Comment by danielduquemelo** [comment]
Criada a conexão entre as tabelas.
sempre que um evento é adicionado ou editado na tabela de poço aberto, chama a atualização de poço revestido
