### ISSUE TITLE
Corrigir peso de lama no evento partial evacuation

### ISSUE THREAD

**Issue by JDVelilla** [PHydra/Hydra#132]
o peso de lama não deve aparecer na tebela principal  o valor deve ser trocado por '-'

**Comment by danielduquemelo** [comment]
Corrigida a leitura dos eventos de partial e full evacuation.

No full evacuation, quando o kernel cria os eventos, ele verifica o ultimo peso de lama válido, corrigindo o peso nos eventos de creep entre dois eventos de full evacuation.
