### ISSUE TITLE
Criar uma pasta que contem todos os arquivos de cada analise submetida

### ISSUE THREAD

**Issue by JDVelilla** [PHydra/Hydra#133]
Ao gerar uma analise, todos os arquivos relacionados deverão ficar numa pasta só com o nome da analise realizada

**Comment by danielduquemelo** [comment]
O diretório da pasta é salvo nos dados de análise do KERNEL com o nome da análise.
A interface altera o diretório das análises (working directory) sempre que o usuário submeter pelo Hydra,e após o envio da análise retorna para o diretório inicial.

**Comment by jorelanjos** [comment]
Pessoal, ao tentar visualizar uma simulação pelo menu do JOB o Abaqus está procurando o ODB na pasta errada.

![image](https://user-images.githubusercontent.com/22779284/39200514-c206c47e-47c2-11e8-8051-4bc0e15f7c7e.png)

**Comment by danielduquemelo** [comment]
Essa questão dos resultados terá que ser resolvida pelo botão "resultados" do próprio Hydra

**Comment by danielduquemelo** [comment]
quanto as pastas, já foi anterado para C:\Temp\Hydra\Nome_do_poço\Nome_da_Análise
