### ISSUE TITLE
Simulação com 2 revestimentos

### ISSUE THREAD

**Issue by lfmabr** [PHydra/Hydra#154]
Problema para simular qualquer caso com 2 revestimentos (pipe in pipe).

## Caso 2:
[erro dois tubos.txt](https://github.com/PHydra/Hydra/files/1984083/erro.dois.tubos.txt)

* Problema a simular
![image](https://user-images.githubusercontent.com/22779284/39755849-bd838866-529d-11e8-8227-20f3ac4aa393.png)

* Etapas e eventos sem nenhum carregamento
![image](https://user-images.githubusercontent.com/22779284/39755874-d113c170-529d-11e8-8797-8fff5999feb8.png)

* Erro reportado
![image](https://user-images.githubusercontent.com/22779284/39755959-0c7cfe70-529e-11e8-9c30-0831da6bbcc5.png)

**Comment by danielduquemelo** [comment]
tem o .hy?

**Comment by lfmabr** [comment]
Caso 1:

Profundidade de análise: 4147 m
Arquivo hy:


[9-BR-82D-RJS_liner7.zip](https://github.com/PHydra/Hydra/files/1984130/9-BR-82D-RJS_liner7.zip)

**Comment by danielduquemelo** [comment]
fiz algumas correções aqui quando as superfícies, e estão rodando.
Este era o problema quando se colocava o revestimento. Este erro não existia nas versões anteriores, devemos ter feito algumas mudanças na determinação das geometrias.

**Comment by danielduquemelo** [comment]
Quanto ao erro que foi reportado na mensagem,  esse erro não apareceu aqui para mim.

" Elements cannot be added using model change"

Foi feita alguma alteração no .CAE ??

**Comment by danielduquemelo** [comment]
Jorel, Fiz alguns testes aqui e não obtive nehum erro. Estou fechando essa issue e enviaremos a versão hoje
