### ISSUE TITLE
Pefil Geotérmico default

### ISSUE THREAD

**Issue by bismarckjunior** [PHydra/Hydra#17]
- [ ] Inicializar o perfil geotérmico com o plugin 
 - [ ] Este perfil não poderá ser removido
 - [ ] Deverá ser o padrão em **Etapas e Eventos**

**Comment by jorelanjos** [comment]
@bismarckjunior e @JDVelilla, o geotérmico é o perfil _default_ tanto para a perfuração quanto para o revestimento.
![capture](https://cloud.githubusercontent.com/assets/22779284/24550466/8819eda0-15f4-11e7-991e-79bbcb3b0ff4.PNG)

Os demais eventos ao serem criados devem inicialmente estar com o perfil de temperatura **inalterado**.
![inalterado](https://cloud.githubusercontent.com/assets/22779284/24551321/644edd50-15f8-11e7-9271-bb796cf55b47.PNG)
