### ISSUE TITLE
Cimento default

### ISSUE THREAD

**Issue by PHydra** [PHydra/Hydra#23]
Definir cimento padrão para todas as análises. @jorelanjos

**Comment by jorelanjos** [comment]
Nome "Pasta convencional 15% NaCl" 
* E=12.7 GPa
* v = 0.25
* phi = 13º
* C = 14.9 MPa
* rho = 15.8 ppg

**Comment by ismaelpimentel** [comment]
@jorelanjos, Por favor, para esses dados do sal acima mencionados, quais são os valores da **Expansão Térmica, Condutividade e Calor Específico**.

**Comment by jorelanjos** [comment]
@ismaelpimentel, seguem os dados solicitados. Favor considerar a pasta de 15% NaCl com as mesmas propriedades térmicas da pasta com 36%.

![prop cimento 36 nacl](https://cloud.githubusercontent.com/assets/22779284/26359381/b4f788a6-3fab-11e7-9f05-018eaefd67ca.PNG)

**Comment by ismaelpimentel** [comment]
Recebi @jorelanjos, obrigado.
