### ISSUE TITLE
Adicionar coluna de cimento

### ISSUE THREAD

**Issue by bismarckjunior** [PHydra/Hydra#3]
No item **Dados Básicos > Tubos e Sapatas**:
É válido a ideia de inserir uma coluna do cimento utilizado para cada fase ?
Isso porque é necessário informar em algum lugar quais as propriedades do cimento estão assoadas para cada fase.
Esta coluna ficaria localizada entre _T.O.C_ e _Mw_ (conforme a figura) e teria como opções os tipos de cimentos criados em **Dados Materiais>Cimentos**.

![duvida_cimento](https://cloud.githubusercontent.com/assets/4762941/22826421/824d8572-ef79-11e6-857b-02f410feb94b.PNG)

**Comment by jorelanjos** [comment]
Como utilizamos praticamente a mesma pasta de cimento para todo o poço, ela tradicionalmente não entre nessa parte.

Precisaremos selecionar o cimento para todo o poço.

**Comment by bismarckjunior** [comment]
Poderíamos, então, colocar uma coluna de checkBox para escolher qual cimento utilizar em: **Dados Materiais > Cimentos**, conforme a figura abaixo?

![solucao_cimento](https://cloud.githubusercontent.com/assets/4762941/22932405/ef2b858a-f2ae-11e6-9424-621f07598c39.png)

**Comment by jorelanjos** [comment]
Perfeito, estou de acordo @bismarckjunior .

**Comment by bismarckjunior** [comment]
Ok

**Comment by bismarckjunior** [comment]
Feito!
