### ISSUE TITLE
Abaqus 6.14 - Matplotlib

### ISSUE THREAD

**Issue by PHydra** [PHydra/Hydra#32]
Verificar se é possível instalar o pacote matplotlib no Python 2.7 no Abaqus 6.14 via PIP

**Comment by bismarckjunior** [comment]
Já estou quase dizendo que não dá, de tanto que já tentei... :(

**Comment by jorelanjos** [comment]
Tranquilo @bismarckjunior, se esse for o veredito, continuaremos como estamos.

De qualquer forma, precisamos migrar para a versão do Abaqus 6.14 para usarmos os recursos da issue #52.

**Comment by bismarckjunior** [comment]
Não consegui. Mas esse deve ser um problema recorrente com quem tenta programar plugins para o Abaqus. Talvez algum fórum da SIMULIA possa ajudar.

**Comment by jorelanjos** [comment]
Bom, estrutura uma pergunta bem detalhada que eu passo para a Simulia.

**Comment by bismarckjunior** [comment]
Hi,
I am developing a plugin for Abaqus using abaqusGui module. I want to use some external
module in my codes and in ABAQUS prompt.
  
I tried to:
  1. Install PIP using "get-pip.py" in ABAQUS folder and use Windows prompt;
  2. Create a Python file that imports and uses pip and run using ABAQUS Python;
  3. Do steps 1 and 2 with a Windows Python with same version;
  4. Install modules in Windows Python and copy the folder to ABAQUS folder;
  5. Install modules using "whl" files in Windows Python and ABAQUS Python;

  I use 6-12 and 2017 versions, but several error appeared.


So:
  1. How can I install a external Python module (e.g. scipy and matplotlib) in ABAQUS?
  2. How can I update existing modules (e.g. numpy)?

**Comment by bismarckjunior** [comment]
Com a ajuda da SIMULIA foi possível instalar o matplotlib no ABAQUS 2017. O passo a passo para instalação encontra-se no link: https://gist.github.com/bismarckjunior/2c58f3059024383d2a9bc08e5082db32.

**Comment by jorelanjos** [comment]
Perfeito @bismarckjunior, para a próxima versão do Hydra colocamos os gráficos com matplotlib.

**Comment by jorelanjos** [comment]
@bismarckjunior por algum motivo não consigo acessar seu link aqui da PETROBRAS.

Você poderia colocar esse passo a passo na página do Hydra? Pode colocar no menu **CODE**.

**Comment by bismarckjunior** [comment]
Jorel, coloquei ontem aqui dentro ba seção wiki.
