### ISSUE TITLE
Acoplamento Gui e Kernel - Básico

### ISSUE THREAD

**Issue by PHydra** [PHydra/Hydra#33]
Criar materiais:
 - [x] Rochas
 - [x] Litologia
 - [x] Tubos
    - [x] Seção Transversal
 - [x] Revestimentos
 - [x] Cimentos

Considerações:
 * As propriedades do fluido, como a densidade (1258, SI), elasticidade (1; 0,1, SI), condutividade(0.12, SI), calor especifico(2000,0, SI) e o modulo de Bulk(1800000000, SI) foram  inicialmente, utilizados na análise  como valores default.

**Comment by ismaelpimentel** [comment]
Esse issue foi dividido em três partes: 
1) Básico (issuse #33)
2) Eventos (issue #38)
3) Geopressoes (issue #38)
