### ISSUE TITLE
Acoplamento Kernerl - Geopressoes

### ISSUE THREAD

**Issue by ismaelpimentel** [PHydra/Hydra#38]
Colocar as geopressões para cada camada especificada no item **Litologia**.

A geopressão é adicionada ao Kernel como um PreDefinedField para o Abaqus. 

@jorelanjos, a tensão será obtida de onde?

Opção 1) Será informada a tensão efetiva através do item **Geopressões** como a diferença entre o overburden e a pressão de poros?

Opção 2) A tensão será calculada através das propriedades das camadas (rho*depth)?

Como há duas possibilidades, é possível que haja alguma incoerência.

**Comment by jorelanjos** [comment]
@ismaelpimentel, as tensões serão dados de entrada através das curvas de **geopressões**.

**Comment by ismaelpimentel** [comment]
Então a massa específica de cada rocha não será uma opção para o usuário. A massa específica será calculada em função da tensão efetiva, ok?

**Comment by jorelanjos** [comment]
As tensões na rocha não devem ser calculadas pela integração das densidades porque não necessariamente vamos preencher todas as camadas e com o mesmo detalhe de uma ferramenta como o SEST por exemplo.

Para a versão atual de EPD a massa específica não é necessária, mas para o modelo axi-simétrico será importante. No plugin velho, usavamos a gravidade para iniciar as tensões.

@danielduquemelo, você precisa de densidade nas suas análises axi? Se não, nem precisa cadastrar.

**Comment by bismarckjunior** [comment]
Daniel irá precisar da massa específica na análise AXI, e irá calculá-la pela tabela de overburden.
