### ISSUE TITLE
Inserir Geopressões

### ISSUE THREAD

**Issue by PHydra** [PHydra/Hydra#39]
- [x] Alterar Ini Stress Fill
- [x] Calcular a massa específica de cada material a partir do overburden
- [x] dbRockLayer::Overburden(SvTop, SvBase, ShmaxTop,ShmaxBase,ShminTop, ShminBase)

**Comment by jorelanjos** [comment]
@danielduquemelo precisamos da massa específica para o modelo AXI?

**Comment by danielduquemelo** [comment]
Podemos calcular a partir da tensão no topo e na base : pho = deltaStress/(grav*deltaDepth)

**Comment by jorelanjos** [comment]
Então nao é necessário o cálculo da densidade, pois o modelo não e dinâmico.

A tensão in-situ é suficiente certo?

**Comment by danielduquemelo** [comment]
Certo. O cálculo da densidade será feito apenas no Axissimétrico

**Comment by jorelanjos** [comment]
@danielduquemelo minha dúvida sempre foi para o AXI, para o EPD não precisamos da densidade.

Para as simulações AXI que você realiza é necessário a densidade? Se sim, devemos implementar na versão 1.1 do Hydra.

**Comment by danielduquemelo** [comment]
Sim, é necessária a densidade para o AXI. Mas podemos calculá-la pelas tensões no topo e na base da camada. 
Assim, além do usuário não precisar entrar com mais um dado (densidade), você evita possíveis erros de compatibilidade.

**Comment by danielduquemelo** [comment]
Se forem dadas as tensões, o modelo calcula a densidade automaticamente.
Se não for dada a tensão, o calcula a mesma com base na densidade
Se não for dada nem tensão, nem densidade, o modelo propaga a base da camada anterior com o topo da camada posterior
