### ISSUE TITLE
Reorganizar Tubos e Sapatas

### ISSUE THREAD

**Issue by bismarckjunior** [PHydra/Hydra#4]
Não seria mais intuitivo se reorganizasse o item **Dados Básicos > Tubos e Sapatas**? Da seguinte forma:
1.  Separasse as tabelas em "Dados de Perfuração" e "Dados de Revestimento";
2. Movesse a coluna de OD da broca para a primeira coluna e o OD do revestimento para a tabela abaixo;
3. Associasse a fase ao OD da broca no comboBox (Fase I - 30''), conforme o item **Eventos**;

![duvida_tubos](https://cloud.githubusercontent.com/assets/4762941/22827112/4680e512-ef7d-11e6-92c5-f67607c1ee2d.PNG)

**Comment by jorelanjos** [comment]
Olá Bismarck, essa é a forma convencional dos softwares de projeto de revestimento.

Veja a figura abaixo.

**Comment by bismarckjunior** [comment]
Ok

**Comment by jorelanjos** [comment]
Atualizei meu comentário.
