### ISSUE TITLE
Atualização das Tabelas e Graficos

### ISSUE THREAD

**Issue by PHydra** [PHydra/Hydra#42]
- [x] Atualizar cada tabela sem ter que clicar na propria tabela,
- [x] Atualizar graficos automaticamente na hora de carregar os dados,
- [x] Atualizar o grafico (litologia + tubos e saptas) quando o usuario adicona a litoliga,
- [x] Evitar criar Fase na tabela etapas sem ter preenhido a linha completa na tabela dados gerais do item tubos e sapatas,
- [x] Para a versão teste deixar restrito so para a opção troca de fluido,
- [x]  Ao abrir o plugin adicionar a aba "Model" do abaqus do lado da aba Hydra,
- [x] A partir da segunda linha dos tubos e sapatas, o diâmetro do tubo na tabela específica não atualiza, permitindo o usuário pegar um NW errado, que define um OD errado na segunda tabela.

**Comment by danielduquemelo** [comment]
Erro nos valores de OD na tabela específica de tubos e sapatas. Sempre pega o valor de 7 pol.
Se mudar o OD de uma linha, não apaga o valor antigo da lista específica.

**Comment by danielduquemelo** [comment]
primeiro item será resolvido na issue #98
