### ISSUE TITLE
Cadastrar tubos de grande diâmetro

### ISSUE THREAD

**Issue by jorelanjos** [PHydra/Hydra#47]
@ismaelpimentel, favor cadastrar os tubos de grande diâmetro.
[CARDAPIO 2013_v2_Jorel.zip](https://github.com/PHydra/Hydra/files/1059305/CARDAPIO.2013_v2_Jorel.zip)

**Comment by ismaelpimentel** [comment]
Ta bom Jorel, farei.

**Comment by danielduquemelo** [comment]
Jorel,
Eu vou fazer essa tarefa.

Você tem o cardápio desses tubos disponíveis, ou eu pego os dados do site da Vallourec?

**Comment by jorelanjos** [comment]
Olá @danielduquemelo dentro do .ZIP que está em anexo tem os dados.
![grande diametro](https://user-images.githubusercontent.com/22779284/26939192-f29027ce-4c4c-11e7-9dcb-6a4733aeea72.PNG)

**Comment by danielduquemelo** [comment]
Perfeito. não tinha visto o .zip

**Comment by danielduquemelo** [comment]
feito
