### ISSUE TITLE
Correção de detalhes da interface

### ISSUE THREAD

**Issue by jorelanjos** [PHydra/Hydra#5]
Pessoal, segue vário _issues_ abertos anteriormente (17/01) para serem corrigidos na interface.
[[2017.01.17] Plug-in_Integridade_Gtep_19Dezembro2016.pptx](https://github.com/PHydra/Hydra/files/793403/2017.01.17.Plug-in_Integridade_Gtep_19Dezembro2016.pptx)

**Comment by bismarckjunior** [comment]
Jorel, a versão que você testou foi totalmente reescrita de forma a tornar o código mais legível e organizado. Dessa forma, será necessário que reavalie os seus comentários em cima da nova versão que inclusive já possui algumas da sugestões (slides 2, 3 e 4 ).

No slide 5, foi mencionado que o OD não é possível de editar. Esse valor é bloqueado e só poderá ser editado na tabela acima (Dados Gerais). 

No slide 6, foi mencionado para atualizar os padrões de litologia, porém não entendi tal comentário. Favor verificar a nova versão.

**Comment by bismarckjunior** [comment]
As correções de detalhes na visualização serão deixadas para etapa final da entrega do projeto. Essa Issue foi movida para Issue #12
