### ISSUE TITLE
kernel - Múltiplos repasses

### ISSUE THREAD

**Issue by danielduquemelo** [PHydra/Hydra#50]
opção de criar diversos repasses

**Comment by danielduquemelo** [comment]
Feito!

**Comment by jorelanjos** [comment]
Show, pode colocar uma figura mostrando os vários repasses?

**Comment by danielduquemelo** [comment]
Coloquei um vídeo no slack...
https://hydra-plugin.slack.com/files/U5ARTBSRZ/F962CGB7B/multiplos_repassesmp4.mp4
