### ISSUE TITLE
GUI: Etapas e Eventos

### ISSUE THREAD

**Issue by JDVelilla** [PHydra/Hydra#57]
- [x] Bloquear a Coluna fim das tabelas Poço Aberto e Poço Revestido de tal jeito que o usuario somente vai escolher o inicio da operação, assim o fim ira ser calculado automaticamente
- [x] Repasse é instantâneo, então não terá coluna fim (passar para o Kernel o tempo de 1 segundo = (1/86400) dias
- [ ] Alargamento: o diâmetro deverá ser definido. O valor do diâmetro entra no nome padrão do evento (ex. Alargamento13_375 --> alargamento do poço com broca de 13 5/8)

**Comment by danielduquemelo** [comment]
Os nomes padrão dos eventos estão na issue #106.

Atualizada a duração! só se entra com o valor da duração
A tabela corrige automaticamente os eventos que não possuem duração definida.
valores de duração padrão aplicados (MudDrop e partial evac. = 7 dias, full evac. = 14 dias)
a duração da perfuração é automaticamente calculada quando se tem o ROP e o comprimento perfurado. Caso o usuário coloque um valor maior, fica o valor maior. Caso coloque um valor menor, ele volta para o valor de L/ROP.
