### ISSUE TITLE
GUI: Análises (específica) - Modelo temporário

### ISSUE THREAD

**Issue by JDVelilla** [PHydra/Hydra#58]
- [x] Gerar o modelo somente na hora do usuario dar click no botão OK
- [x] Caso o usuario clicar no botão aplicar e depois fechar a janela, deve-se criar um modelo temporario

**Comment by danielduquemelo** [comment]
atualizado a criação dos modelos temporários utilizando o nome model-1 padrão do abaqus. atualizado o carregamento inicial da geometria temporária
