### ISSUE TITLE
Implementar as telas de EVENTOS

### ISSUE THREAD

**Issue by jorelanjos** [PHydra/Hydra#6]
@bismarckjunior 
Segue modelo de interface sugerida para os módulos de EVENTOS
![eventos](https://cloud.githubusercontent.com/assets/22779284/23212285/b7f0407e-f8e4-11e6-85d5-09105b31b56e.PNG)

Segue Excel, mostrando o modelo conceitual.
[[2016.12.19] modelo EVENTOS.xlsx](https://github.com/PHydra/Hydra/files/793420/2016.12.19.modelo.EVENTOS.xlsx)

**Comment by jorelanjos** [comment]
@bismarckjunior 
Avaliar os comentários feitos dentro da tela do Hydra.
![eventos_abaqus](https://cloud.githubusercontent.com/assets/22779284/23212467/a0b6ae2e-f8e5-11e6-8f06-12cc21dc8007.PNG)

**Comment by bismarckjunior** [comment]
Uma versão preliminar da seção Eventos já foi finalizada, como gostaria de testá-la?

**Comment by jorelanjos** [comment]
@bismarckjunior, faz um _deploy_ do código para eu baixar aqui e testar. Estou cadastrando todas as solicitações anteriores, nem que seja para deixar de registro.

Obrigado.

**Comment by bismarckjunior** [comment]
Enviei uma versão teste (Hydra 0.1) para o @JDVelilla , amanhã ele irá te apresentar.

**Comment by PHydra** [comment]
Modificações no item **Etapas e Eventos** será dividida em diversas issues como #24, #25 e #26.
