### ISSUE TITLE
KERNEL: Degradação térmica

### ISSUE THREAD

**Issue by danielduquemelo** [PHydra/Hydra#65]
- [x] Correção do Limite de Escoamento de acordo com a temperatura do aço ( tabela de Limite de escoamento)
 - [x] fazer a leitura da degradação no grau do material

**Comment by danielduquemelo** [comment]
@jorelanjos, você poderia passar esses valores de degradação para cada grau?

**Comment by jorelanjos** [comment]
@danielduquemelo segue os dados que dispomos da Vallourec, mas em email eu solicitei ao pessoal do SCORE, que fossem enviadas as tabelas já resumidas.
[2014_02_28_RDPE_2014-0464_YS_derating_rev0.zip](https://github.com/PHydra/Hydra/files/1601292/2014_02_28_RDPE_2014-0464_YS_derating_rev0.zip)

No entanto, podemos implementar a degradação térmica como um cardápio, similar ao "seção transversal", onde teremos a degradação térmica default (já implementada), quando tivermos todos os aços definidos, ai associamos em materiais.

**Comment by danielduquemelo** [comment]
Enquanto não temos o item Degradação térmica na interface, a correção é feita no Kernel.

A temperatura utilizada para a correção (fator multiplicador) é a temperatura da rohca (perfil geotérmico)

**Comment by jorelanjos** [comment]
@danielduquemelo avaliar se esta _issue_ está de fato atendida, pois ao simular no Abaqus não observei a degradação do limite de escoamento do _Properties_.
