### ISSUE TITLE
Implementar tela de ANÁLISE

### ISSUE THREAD

**Issue by jorelanjos** [PHydra/Hydra#7]
@bismarckjunior, Abaixo segue fluxograma desejado para o módulo de ANÁLISE:
[[2016.12.19] modelo análise HYDRA.xlsx](https://github.com/PHydra/Hydra/files/793437/2016.12.19.modelo.analise.HYDRA.xlsx)

Seguem os comentários realizados anteriormente após primeiras implementações:
[[2016.12.19] Plug-in_Integridade_Gtep_19Dezembro2016_ANÁLISE.pptx](https://github.com/PHydra/Hydra/files/793502/2016.12.19.Plug-in_Integridade_Gtep_19Dezembro2016_ANALISE.pptx)

**Comment by bismarckjunior** [comment]
A refatoração do código ainda não foi finalizada, conforme pode ser visto pela Issue #1 . Atualmente estou trabalhando na construção da tela Análise. Tive diversas dúvidas de como construí-la tendo em mãos estas sugestões e a ajuda do Ismael e do Juan. Já consegui pensar em uma forma de fazer os layouts. Assim que terminar, irei disponibilizar para aprovação/teste, porém apenas a carcaça. Depois de aprovada, será introduzido o código relativo a interface (conexão com as outras tabelas).

**Comment by bismarckjunior** [comment]
Modificar a criação do item análise conforme o diagrama abaixo. 

Não haverá mais subitens pendurados na analise. O clique no item análise irá exibir o resumo.

![layout_analise](https://cloud.githubusercontent.com/assets/4762941/24402227/0209c748-138e-11e7-9003-655b633a2748.png)

**Comment by PHydra** [comment]
Issue movida para #34
