### ISSUE TITLE
GUI: Graus (Dados Materiais)

### ISSUE THREAD

**Issue by danielduquemelo** [PHydra/Hydra#73]
- [x] Reestruturação do item material tubes. 
  - [x] Criação de duas novas classes, HyTableFrame_Tubes e HyTableFrame_Grau, para uma maior mobilidade do item tubes.
- [x] Criar um Botão para gerenciar o aparecimento da tabela de Graus. A tabela propriedade de graus irá ficar visível dependendo do click do usuário.

**Comment by ismaelpimentel** [comment]
Feito
