### ISSUE TITLE
Implementar novos Ícones na tela TREE

### ISSUE THREAD

**Issue by jorelanjos** [PHydra/Hydra#8]
Trocar o ícones de colapsar a tela:
![button_2-512](https://cloud.githubusercontent.com/assets/22779284/23213326/52fae818-f8e9-11e6-85c2-d537debf6770.png)

Trocar os ícones pelos do PoçoWEB, esses eu preciso passar para vocês.
[[2016.12.19] Plug-in_Integridade_Gtep_19Dezembro2016_DADOS_BÁSICOS.pptx](https://github.com/PHydra/Hydra/files/793513/2016.12.19.Plug-in_Integridade_Gtep_19Dezembro2016_DADOS_BASICOS.pptx)

**Comment by bismarckjunior** [comment]
Na nova versão, todos os ícones foram redesenhados. Caso não tenha interesse em vê-los, será necessário enviar todos os ícones em uma qualidade superior.

**Comment by jorelanjos** [comment]
Perfeito então, assim que ver a nova versão eu comento.

**Comment by bismarckjunior** [comment]
Os ícones serão mantidos a menos que seja solicitado a troca. Com relação ao  item de colapso da tela, o Abaqus diminui a qualidade da imagem ao bloquear a imagem. Dessa forma quando a janela está estendida, o botão de abrir a janela fica bloqueado e a imagem com uma baixa qualidade. O mesmo acontece quando a janela está colapsada.
