### ISSUE TITLE
BUG: Poço está abrindo

### ISSUE THREAD

**Issue by jorelanjos** [PHydra/Hydra#82]
@ismaelpimentel, na versão 0.1.8 ao rodar o exemplo abaixo para 5000m o poço está aumentando o diâmetro em vez de fechar.

@danielduquemelo estou te copiando para ciência.

**OBS:  tem que alterar a extensão do arquivo de .txt para .hy**
[BUZ5_V3.txt](https://github.com/PHydra/Hydra/files/1397998/BUZ5_V3.txt)

Simulação feita a 5000m
![capture2](https://user-images.githubusercontent.com/22779284/31766761-f4f3eaea-b49e-11e7-97d4-52530d278d7c.PNG)

Pela tela de geopressões da para observar que a pressão de poros é zero.
![capture](https://user-images.githubusercontent.com/22779284/31766731-d9917420-b49e-11e7-8ba4-e2b175c93657.PNG)

Ao verificar as tensões iniciais temos um valor muito baixo (11.4MPa).
![capture3](https://user-images.githubusercontent.com/22779284/31766824-358ad53c-b49f-11e7-96f5-39b1d3b56a42.PNG)

**Comment by danielduquemelo** [comment]
Quando a Basse da rocha estava na mesma profundidade de um dado de geopressões, não estava acontecendo a correção de valores de ppg para MPa. Nesse caso, o kernel aplicava a tensão da rocha como o seu valor em ppg.

correção: MPa = ppg*grav*depth
