### ISSUE TITLE
Configuração (default) tela de análise

### ISSUE THREAD

**Issue by jorelanjos** [PHydra/Hydra#83]
Pessoal, peço que coloquem o modelo com as seguintes características _default_.
![capture](https://user-images.githubusercontent.com/22779284/31945485-ae1b107a-b8a5-11e7-900e-1ac980cedd69.PNG)

**Comment by ismaelpimentel** [comment]
Ta bom Jorel.

Atenciosamente

Pimentel

2017-10-24 11:25 GMT-02:00 Jorel Anjos <notifications@github.com>:

**Comment by ismaelpimentel** [comment]
Feito.
