### ISSUE TITLE
Bug: Ao criar análise está dando crash

### ISSUE THREAD

**Issue by jorelanjos** [PHydra/Hydra#84]
Pessoal, peço que façam o diagnóstico da falha ao criar a análise em 3545m.

Ao criar a análise o programa está dando crash.

É um caso de simulação do nosso principal cliente. 
[sim_celso.txt](https://github.com/PHydra/Hydra/files/1468391/sim_celso.txt)

**Comment by ismaelpimentel** [comment]
Ta bom Jorel. Boa noite

**Comment by ismaelpimentel** [comment]
Foram encontrados e solucionados problemas tanto na interface como no kernel. O problema na interface foi no item step e eventos no momento de pegar os dados do poço revestido da interface para enviar para o kernel. 

O problema do Kernel foram:
1) Ao capturar os dados de temperatura da rocha, a temperatura do topo não era atualizada. Quando as camadas de rocha eram divididas no Kernel (em profs. de TOC, Sapata, e etc.) esses valores eram extrapolados erradamente.
2) Fases que apresentavam varias seções de tubos diferentes eram tratadas como anulares diferentes. Assim, os eventos daquela fase eras selecionados erradamente. Corrigido através do link entre os revestimentos e a fase nos quais eles se encontravam.
