### ISSUE TITLE
Item Litologia

### ISSUE THREAD

**Issue by jorelanjos** [PHydra/Hydra#9]
Seguir recomendações apresentadas abaixo:
[[2016.12.19] Plug-in_Integridade_Gtep_19Dezembro2016_LITOLOGIA.pptx](https://github.com/PHydra/Hydra/files/793527/2016.12.19.Plug-in_Integridade_Gtep_19Dezembro2016_LITOLOGIA.pptx)

**Comment by bismarckjunior** [comment]
Slide 1: Já foi modificado na nova versão

Slide 2:  Acredito que os diagramas são similares ao SEST, visto que foi baseando-se lá que o Juan criou as imagens. Irei conversar com ele.

**Comment by jorelanjos** [comment]
Pega as imagens com a Carla, pois tem algumas desatualizadas, principalmente para o sal.

**Comment by bismarckjunior** [comment]
Então, @JDVelilla ficará encarregado desta tarefa
