### ISSUE TITLE
Detalhamento dos Carregamentos e Eventos

### ISSUE THREAD

**Issue by jorelanjos** [PHydra/Hydra#94]
@ismaelpimentel segue detalhamento das telas de carregamentos.
[Tela CARREGAMENTOS.pptx](https://github.com/PHydra/Hydra/files/1543781/Tela.CARREGAMENTOS.pptx)

**Comment by ismaelpimentel** [comment]
Recebi.

Farei essas modificações.

Saudações

2017-12-08 18:43 GMT-02:00 Jorel Anjos <notifications@github.com>:

**Comment by danielduquemelo** [comment]
essa issue já existia em #37
