### ISSUE TITLE
Falha no contato entre o sal e o cimento

### ISSUE THREAD

**Issue by ismaelpimentel** [PHydra/Hydra#95]
- [ ] Alterar a superfície do INTERACTION para o *self contact. Baseado na definição de contato do sal/revestimento o contato sal/cimento também deve ser definido como "self contato".  As duas primeiras figuras em anexo exemplificam o contato entre o sal e o cimento no inicio do contato e no fim da simulação. A terceira figura em anexo mostra as superfícies que precisam ser definidas o contato:

![iniciocontato](https://user-images.githubusercontent.com/12529868/33934900-545e3dce-dfe1-11e7-8891-6f04be0d195a.gif)

![fimsimulacao](https://user-images.githubusercontent.com/12529868/33934918-5c0f4ee6-dfe1-11e7-9da9-dcd036a774e8.gif)

![selfcontato](https://user-images.githubusercontent.com/12529868/33934939-6950959c-dfe1-11e7-97ae-8967c55eb4e4.gif)

**Comment by PHydra** [comment]
solução feita dependente da malha. o nó em comum entre as superfícies é eliminado do Set da rocha. (escrito por Daniel)
