### ISSUE TITLE
Carregamento sumindo após criação da análise

### ISSUE THREAD

**Issue by jorelanjos** [PHydra/Hydra#98]
Pessoal, estou tendo um problema que já ocorreu no passado com o @lfmabr, após a criação de uma análise, alguns carregamentos estão sumindo.

Abaixo segue um passo a passo do que está ocorrendo.
[Bug - carregamento sumindo após criação de evento.pptx](https://github.com/PHydra/Hydra/files/1569203/Bug.-.carregamento.sumindo.apos.criacao.de.evento.pptx)

Segue também o arquivo .hy usado.
[CQ_v2.txt](https://github.com/PHydra/Hydra/files/1569208/CQ_v2.txt)

Segue o CAE:
[CQ.zip](https://github.com/PHydra/Hydra/files/1569303/CQ.zip)

**Comment by ismaelpimentel** [comment]
Feito
